If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Compiler: gcc
  Add: [-ferror-limit=0]

---

If:
  PathMatch: [.*\.cpp, .*\.hpp, .*\.h]
CompileFlags:
  Compiler: g++
  Add: [-std=c++2b, -ferror-limit=0]
